### ISSUE TITLE
UnboundLocalError: local variable 'rU' referenced before assignment

### ISSUE THREAD

**Issue by KSteffen** [knightlab-analyses/multiomic-cooccurrences#13]
Hello!
Thank you for this nice tool! I installed mmvec through conda and run it in it's own environment.
It seems to work for my complete input data set (metabolome and microbiome of three species of animals).
` mmvec paired-omics --microbe-file microbiome_KS.biom --metabolite-file metabolome_KS.biom --summary-dir test_dir/`

However, I wanted to focus on linking microbiome and metabolome for one species only. When running the same command on the subsets, it produces an error message and only generate one file (events.out.tf....).

```
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/anaconda2/envs/mmvec-env/bin/mmvec", line 224, in <module>
    mmvec()
  File "/anaconda2/envs/mmvec-env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda2/envs/mmvec-env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/anaconda2/envs/mmvec-env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/anaconda2/envs/mmvec-env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda2/envs/mmvec-env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/anaconda2/envs/mmvec-env/bin/mmvec", line 171, in paired_omics
    checkpoint_interval=checkpoint_interval)
  File "/anaconda2/envs/mmvec-env/lib/python3.7/site-packages/mmvec/multimodal.py", line 274, in fit
    self.U = rU
UnboundLocalError: local variable 'rU' referenced before assignment
```

How do I tackle this? 
Thank you for your help!

**Comment by mortonjt** [comment]
@KSteffen , is this running with your own dataset?  If so, could you raise this on the git issue tracker on the [mmvec repo](https://github.com/biocore/mmvec/issues)? And could you include the exact command that you ran to reproduce the error?

There was an identical error [here](https://github.com/biocore/mmvec/issues/103) that was raised when passing in the wrong files.

Also, this method will not work on individual microbe/metabolites - for the same reason that PCA doesn't work with a single microbe. It will work on subsets, but those subsets need multiple species.
